/* interface.h : Impala interface file generated by impala */
#ifndef INTERFACE_H
#define INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif

struct Color {
    float r;
    float g;
    float b;
};

struct PixelData {
    struct Color* pixels;
    int width;
    int height;
};

struct Vec3 {
    float x;
    float y;
    float z;
};

struct Bvh8Node {
    float bounds[6][8];
    int child[8];
    int pad[8];
};

struct Bvh4Tri {
    float v0[3][4];
    float e1[3][4];
    float e2[3][4];
    float n[3][4];
    int id[4];
};

struct Bvh8Tri4 {
    struct Bvh8Node const* nodes;
    struct Bvh4Tri const* tris;
};

struct Vec2 {
    float x;
    float y;
};

struct TriMesh {
    struct Vec3 const* normals;
    struct Vec3 const* face_normals;
    struct Vec2 const* uvs;
    int const* ids;
    int num_tris;
};

void render(void);

#ifdef __cplusplus
}
#endif

#endif /* INTERFACE_H */

