/* traversal.h : Impala interface file generated by impala */
#ifndef TRAVERSAL_H
#define TRAVERSAL_H

#ifdef __cplusplus
extern "C" {
#endif

struct Bvh2Tri {
    float v0[3];
    float nx;
    float e1[3];
    float ny;
    float e2[3];
    int id;
};

struct Bvh4Node {
    float min[3];
    float max[3];
    int child[4];
};

struct Bvh4Tri {
    float v0[3];
    float e1[3];
    float e2[3];
    float n[3];
    int id[4];
};

struct Bvh4 {
    struct Bvh4Node* nodes;
    struct Bvh4Tri* tris;
};

struct Bvh2BBox {
    float lo_x;
    float hi_x;
    float lo_y;
    float hi_y;
    float lo_z;
    float hi_z;
};

struct Bvh2Node {
    struct Bvh2BBox left_bb;
    struct Bvh2BBox right_bb;
    int left;
    int right;
    int pad1;
    int pad2;
};

struct Bvh2 {
    struct Bvh2Node* nodes;
    struct Bvh2Tri* tris;
};

struct RayAoS {
    float org[3];
    float tmin;
    float dir[3];
    float tmax;
};

struct HitAoS {
    int tri_id;
    float t;
    float u;
    float v;
};

void frontend_cpu_traverse_bvh(struct Bvh4* bvh, struct RayAoS* rays, struct HitAoS* hits, int ray_count);
void frontend_gpu_traverse_bvh(struct Bvh2* bvh, struct RayAoS* rays, struct HitAoS* hits, int ray_count);

#ifdef __cplusplus
}
#endif

#endif /* TRAVERSAL_H */

